coverage:
    status:
        project:
            default:
                target: 90 # otherwise any regression in code coverage fails the build
                threshold: 2%
                # range: 75...100
                # round: down
                # precision: 2
                if_ci_failed: success
                flags:
                    - Apex
                    - LWC
        patch: off
github_checks: false