coverage:
  status:
    project:
      default:
        target: 90
        threshold: 2%
        if_ci_failed: success
        flags:
          - Apex
          - LWC
    patch: off
github_checks: false
comment:
  behavior: new
