coverage:
    status:
        project:
            default:
                base: 90 # otherwise any regression in code coverage fails the build
                range: 75...100
                round: down
                precision: 2
                if_ci_failed: success
        patch: off